docs/usage/addresses.rst, docs/usage/applications.rst, docs/usage/caller-ids.rst, docs/usage/conferences.rst, docs/usage/errors.rst, docs/usage/messages.rst, docs/usage/notifications.rst, docs/usage/phone-calls.rst, docs/usage/phone-numbers.rst, docs/usage/queues.rst, docs/usage/recordings.rst, docs/usage/sip.rst, docs/usage/transcriptions.rst, docs/usage/twiml.rst, docs/usage/validation.rst
Updates some indentation to be two spaces (more Ruby like).
Also corrects some syntax errors, including missing `end` keywords.
=> Corrects docs

.travis.yml
[More about TravisCI and containers here](http://docs.travis-ci.com/user/workers/container-based-infrastructure/).
=> Ruby 2.2, TravisCI containerized inf

twilio-ruby.gemspec
Bumping up version of jwt to 1.2.0. Thanks!
=> update jwt version

README.md, docs/index.rst, docs/usage/lookups.rst
This is a first pass at some documentation for the Lookups API. Thanks to @radar raising this issue in #149.
=> Adds documentation for the Lookups API

lib/twilio-ruby/rest/task_router/statistics.rb, spec/rest/task_router/statistics_spec.rb
=> Pass URL parameters through for task router statistics

lib/twilio-ruby/rest/lookups/phone_numbers.rb, spec/rest/lookups/phone_number_spec.rb
=> URI encode phone number lookups

docs/usage/token-generation.rst
=> Demonstrate outgoing params

lib/twilio-ruby/task_router/workflow_builder.rb, spec/task_router/workflow_builder_spec.rb
Handle parsing both friendly_name and filter_friendly_name
Add a Workflow Builder test
=> TaskRouter Workflow Parsing handles filter_friendly_name and friendly_name

README.md, lib/twilio-ruby/twiml/messaging_response.rb, lib/twilio-ruby/twiml/voice_response.rb, spec/twiml/messaging_response_spec.rb, spec/twiml/voice_response_spec.rb
Optional parameter on Dial and Message
=> Optional parameter on Dial and Message

examples/examples.rb
=> fcorrect documentation

spec/jwt/access_token_spec.rb
Keeps the test output nice and tidy 😄
=> Silence deprecation messages within tests for Grants

lib/rack/twilio_webhook_authentication.rb, lib/twilio-ruby.rb, lib/twilio-ruby/security/request_validator.rb, lib/twilio-ruby/util/configuration.rb, spec/rack/twilio_webhook_authentication_spec.rb, spec/security/request_validator_spec.rb
* Undeprecate Twilio.configure.
* Restore Webhook Auth helper.
This reverts commit 038a3f921bb6ae66063389d9f685ab297042d06a.
=> Restore accidentally removed files.

lib/twilio-ruby/http/http_client.rb
Hey Twilio, this fixes Ruby interpolation for the proxy setting.
=> Fixed proxy interpolation

spec/twiml/voice_response_spec.rb
=> Fix TwiML Say verb spec

lib/twilio-ruby/twiml/twiml.rb
Translate generated attribute names to their XML equivalents.
=> Add attribute overrides from generated code

README.md
=> Fix Say example in README.md

lib/twilio-ruby/twiml/voice_response.rb, spec/twiml/voice_response_spec.rb
=> Fix custom param tests

README.md
=> Add Help Center and Support Ticket links to the README

lib/twilio-ruby/twiml/voice_response.rb
=> Update TwiML docs for naming overrides

lib/twilio-ruby.rb
=> Add TwiML FaxResponse require to top-level file

lib/twilio-ruby/rest/lookups/v1/phone_number.rb, lib/twilio-ruby/rest/pricing/v1/voice/number.rb, lib/twilio-ruby/rest/pricing/v2/voice/number.rb, spec/integration/lookups/v1/phone_number_spec.rb, spec/integration/pricing/v1/voice/number_spec.rb, spec/integration/pricing/v2/voice/number_spec.rb
=> Add URI encoding for phone numbers

.dockerignore, .gitignore, Dockerfile
`make docker-build` now works.
=> Fix the Dockerfile to use the latest Ruby 2.4 and ignore the Gem lock file

lib/twilio-ruby/http/http_client.rb
=> Wrap any Faraday error as a TwilioError

.travis.yml
=> Auto-deploy via Travis CI upon tagged commit to master

lib/twilio-ruby/jwt/task_router.rb
Fixes a typo in JWT::TaskRouterUtils
=> chore: Fix a typo in JWT::TaskRouterUtils

.rubocop.yml, lib/twilio-ruby/framework/error.rb, spec/rest/client_spec.rb, twilio-ruby.gemspec
Adds `details` to the error object. Details are returned by selective apis to populate extra information about errors.
The Studio V2 flow api will be returning extra details with flow validation errors.
=> feat: add details to error object

README.md
There is no clear documentation on how to use an API Key with this library
Show an example.
=> docs:Document how to use an API Key

lib/twilio-ruby/rest/studio.rb
https://issues.corp.twilio.com/browse/DI-702
=> fix: shortcut syntax for new non-GA versions

examples/examples.rb
In `examples/example.rb` example for 'send an mms' uses `media_urls` which returns `ArgumentError: unknown keyword: :media_urls`.  This change updates to use `media_url` which the documentation lists as the current syntax.
=> docs: update mms example to use media_url

.gitignore, .travis.yml, Gemfile, sonar-project.properties, spec/spec_helper.rb
Integrate with sonarcloud with coverage data
=> chore: integrate sonarcloud

lib/twilio-ruby/rest/client.rb, spec/rest/client_spec.rb
Jira Issue: https://issues.corp.twilio.com/browse/DI-2050
=> chore: update the user agent string for twilio-ruby

spec/rest/client_spec.rb
Internal Jira link: [DI-2164](https://issues.corp.twilio.com/browse/DI-2164)
=> fix: useragent regrex unit test for RC branch

lib/twilio-ruby/base/client_base.rb, lib/twilio-ruby/rest/client.rb
=> feat: Add client base file

.github/workflows/test-and-deploy.yml, Makefile, cluster_spec.rb
Add cluster test to 6.0.0-rc branch. A link to a successful run of the github action with cluster test has been added here. 
[https://github.com/twilio/twilio-ruby/actions/runs/4041476494]( https://github.com/twilio/twilio-ruby/actions/runs/4041476494)
=> chore: Add Cluster test to rc branch

.github/workflows/test-and-deploy.yml, README.md
This PR:
Adds support for Ruby 3.2, JRuby 9.3, and JRuby 9.4. 
Relevant PRs: #640 & #638 
=> chore: extend ruby & jruby support

README.md
This assumes the MVR will be 6.0.0 and not something else. If it will be 6.0.1, etc please ensure to set the correct value.
=> docs: update versions in README.me for release

Makefile
=> fix: update Makefile to test changelog genx

CHANGES.md, README.md, lib/twilio-ruby/rest/client.rb, lib/twilio-ruby/rest/preview/deployed_devices/fleet.rb, lib/twilio-ruby/rest/preview/sync/service.rb, lib/twilio-ruby/version.rb
=> chore: sync with main

lib/twilio-ruby/rest/client.rb, lib/twilio-ruby/rest/preview_messaging.rb, lib/twilio-ruby/rest/preview_messaging_base.rb
added domain detail for Preview Messaging
=> chore: add domain detail

lib/twilio-ruby/http/http_client.rb
Removed SSL CA cert as this is not being used
=> chore: removed ssl ca file from http client

.github/workflows/test-and-deploy.yml
=> chore: disable-cluster-test

.github/workflows/test-and-deploy.yml
=> chore: enable cluster test

Gemfile
Adding rexml to Gemfile as it is removed from ruby-head and newer versions
=> chore: adding rexml to Gemfile

Makefile, lib/twilio-ruby/base/client_base.rb
ContentType is required in POST and PUT methods. Adding the support for PUT.
=> chore: adding contentType in post and put

twilio-ruby.gemspec
=> chore: fix documentation link

CHANGES.md, twilio-ruby.gemspec
=> chore: bug fix

.github/workflows/test-and-deploy.yml
JRuby 9.2 has EOL and hence is no more available for testing. So removing its test.
=> chore: removing jruby-9.2

Gemfile, twilio-ruby.gemspec
Fixes this error - https://github.com/twilio/twilio-ruby/actions/runs/12746557333/job/35522819977#step:7:8
=> chore: add ostruct in gemfile

Gemfile, twilio-ruby.gemspec
Adding ostruct and benchmark in gemfile to fix this error - Fixes this error - https://github.com/twilio/twilio-ruby/actions/runs/12746557333/job/35522819977#step:7:8
=> chore: add ostruct and benchmark in gemfile

UPGRADE.md
=> feat!: MVR ready
