twilio/twilio-ruby

lib/rack/twilio_webhook_authentication.rb
spec/rack/twilio_webhook_authentication_spec.rb

Hi,
We are using Twilio with its sub-accounts feature extensively. Our business use-case is such that the Twilio web-hook request comes from the sub-account's TwiML app. Existing Rack while being a sweet convenience, doesn't have the feature to dynamically fetch the Twilio's Auth-Token based on the `AccountSid` of the sub-account. Because this AccountSid is sent with the request params from Twilio, it makes sense to fetch the auth-token for that sub-account from our end.
This PR is a tested patch enhancing the Rack to get auth-token dynamically. How can it be done? Simply pass nil instead of the auth_token argument, making the rack to call the `getAuthToken(account_sid)` method. The end-user can over-ride this method to suit their implementation of fetching the `AuthToken` based on …

Compute auth_token dynamically based on AccoundSid from request params

---

LICENSE.md

Considering use of this gem in a project I'm starting.  License wasn't labeled as MIT.  Ended up visually comparing against a known copy of MIT to be sure.

Make it clear that license is MIT

---

lib/twilio-ruby.rb
lib/twilio-ruby/rest/base_client.rb
lib/twilio-ruby/rest/client.rb
lib/twilio-ruby/rest/lookups_client.rb
lib/twilio-ruby/rest/task_router_client.rb
lib/twilio-ruby/util/client_config.rb
spec/util/client_config_spec.rb
spec/util/configuration_spec.rb

Rather than repeating a mostly similar `DEFAULTS` hash across the REST Clients this pull request introduces a `ClientConfig` object that encapsulates the defaults and allows them to be overridden when they need to be.
Since only one default is overridden at the moment, the `host`, this also includes a class method on the `BaseClient` that can be called on the subclasses to set the relevant host.

Uses configuration object instead of defaults hash for REST clients

---

spec/util/request_validator_spec.rb

The request validator specs were only testing the positive scenario. I added negative scenarios and refactored the spec to avoid duplication.

Add request validator specs to test bad signature

---

lib/twilio-ruby/rest/base_client.rb

[You shouldn't rescue `Exception` in Ruby](http://daniel.fone.net.nz/blog/2013/05/28/why-you-should-never-rescue-exception-in-ruby/). It will rescue `NoMemoryError` and `Interrupt` and others you don't really want to rescue from in this case. `StandardError`, which is the default when just using `rescue`, is better, but ideally this would rescue specific errors that we want to rescue from. Perhaps looking at [Faraday's list of errors](https://github.com/lostisland/faraday/blob/1d71fcab65d0baa0e8abeb26d819856f7d29356d/lib/faraday/adapter/net_http.rb#L12-L24) or [this suggestion from Tammer Saleh](http://tammersaleh.com/posts/rescuing-net-http-exceptions/) would be better. The least we can do is stop rescuing `Exception` though.

Stops rescuing Exception, rescues StandardError instead.

---

lib/twilio-ruby/rest/base_client.rb

First, some background.
I have a Rails app which has a `config/initializers/twilio.rb`:
```ruby
require 'twilio-ruby'
Twilio.configure do |config|
config.account_sid = "[sid]"
config.auth_token = "[auth token]"
end
```
I can successfully use this code to send an SMS:
```ruby
sms_number = "[redacted]"
dialing_code = "+61"
phone_number = "[redacted]"
client = Twilio::REST::Client.new
message = client.account.messages.create({
:from => "#{sms_number}",
:to => "+#{dialing_code} #{phone_number}",
:body => "Your verification code for Bike Exchange is #{verification_code}",
})
```
That works nicely.
Today, I wanted to validate phone numbers and I saw that Twilio now has a lookups API for that. There's no documentation in the README for this gem wrt to lookups, so I had to piece together how to …

Define object in case of Net::HTTPBadRequest

---

lib/twilio-ruby/rest/list_resource.rb

The `total` special attribute was removed in 4.0.0 but there was still mention of it.

Update Twilio::REST::ListResource#list doc

---

lib/twilio-ruby/rest/pricing_client.rb
spec/rest/pricing_client_spec.rb

Fixes messaging pricing being broken. We had defined the subresource but forgot to make it accessible.

Add messaging attribute to pricing_client. 

---

lib/twilio-ruby/task_router/capability.rb
spec/task_router_deprecated_spec.rb
spec/task_router_worker_spec.rb

- Allow fetching Reservations under a Worker by default
- Allow updating Reservations under a Worker

Loading Reservations under a Worker by default in TaskRouter JS SDK

---

lib/twilio-ruby/framework/exception.rb

Hit this bug in 5.0.0.rc14
```
#<NameError: undefined local variable or method `msg' for #<Twilio::REST::RestException:0x007ff1b48599d8>
/Users/matthew/.gem/ruby/2.3.1/gems/twilio-ruby-5.0.0.rc14/lib/twilio-ruby/framework/exception.rb:26:in `to_s'
```

Fix exception in the RestException#to_s method

---

lib/twilio-ruby/twiml/messaging_response.rb
lib/twilio-ruby/twiml/voice_response.rb

The elements `<Hangup>`, `<Reject>`, `<Leave>`, `<Redirect>`, `<Body>`, `<Media>`, `<Say>`, `<Play>`, `<Pause>`, `<Task>`, `<Record>`, `<Sms>`, `<Client>`, `<Conference>`, `<Number>`, `<Queue>`, `<Sip>` and `<Sim>` cannot nest elements within them. So there's no need for them to react to a passed block.
Also, some four space indenting slipped in, returned to two spaces.

Don't allow blocks for TwiML elements that don't nest.

---

lib/twilio-ruby/jwt/access_token.rb
lib/twilio-ruby/jwt/client_capability.rb
lib/twilio-ruby/jwt/jwt.rb
lib/twilio-ruby/jwt/task_router.rb

As discovered in #318, `BaseJWT` defines `to_jwt` but all the subclasses individually define or alias `to_s` to `to_jwt`. This PR tidies that up and aliases `to_s` to `to_jwt` in the base class.

to_s should only be defined in one spot for JWTs.

---

README.md
lib/twilio-ruby/twiml/twiml.rb
spec/twiml/messaging_response_spec.rb
spec/twiml/voice_response_spec.rb

`Twilio::TwiML::TwiML#to_xml` was being aliased to `to_s` before `to_s` was defined so took on the old definition.
This PR adds tests for using `to_xml` and fixes the aliasing. It also removes the reference to [builder](https://rubygems.org/gems/builder/) in the README.

Corrects to_xml in TwiML generation

---

lib/twilio-ruby/http/http_client.rb

We saw a very strange issue when upgrading from 4.x to 5.x where suddenly unrelated HTTP requests had nested params encoded incorrectly. It looks like this is because of [this line](https://github.com/twilio/twilio-ruby/blob/cc8880bf949e03882004bd72854d31c0bc1a41f1/lib/twilio-ruby/http/http_client.rb#L17), where the global default params encoder for all Faraday instances is changed from `Faraday::NestedParamsEncoder` to `Faraday::FlatParamsEncoder`.
This sets the `env.params_encoder` in the Faraday client set up just for Twilio requests, so other API clients are not affected.

Configure params encoder only for Twilio requests

---

twilio-ruby.gemspec

twilio-ruby works with either libxml version 2 or 3.
libxml2 is common enough in other gems that allowing it here will reduce gem conflicts

Allow libxml 2 or 3 [Fixes #315]

---

.travis.yml
lib/twilio-ruby/http/http_client.rb
spec/http/http_client_spec.rb

HttpClient now accepts a `timeout` keyword argument which will be used when making requests to twilio. 
Example of initializing a rest client with a custom timeout:
```ruby
http_client = Twilio::HTTP::Client.new(timeout: 10)
client = Twilio::REST::Client.new('AC123', '<auth>', nil, nil, http_client)
```
Fix for https://github.com/twilio/twilio-ruby/issues/306

Allow configuring timeout globally on HttpClient

---

lib/twilio-ruby/jwt/client_capability.rb

In `appParams` the `&` separator should be URL-encoded.

Fix ClientCapability appParams

---

examples/print_call_log.rb

This example code is not working.
The following error message appears.
```rb
Traceback (most recent call last):
print_call_log.rb:15:in `<main>': undefined method `page' for #<Twilio::REST::Calls:0x00007fd59888e210> (NoMethodError)
```
Change a caliing method page() to list().
It works!

Fixed example code

---

README.md
lib/twilio-ruby/twiml/twiml.rb
lib/twilio-ruby/version.rb
spec/spec_helper.rb
spec/twiml/messaging_response_spec.rb
spec/twiml/voice_response_spec.rb

This leads to XML that has line breaks after each element, which wasn't present before, but doesn't break anything in terms of the expected output. This follows #382 (well, it includes all of #382, but should be separately reviewed), which updated the tests to not worry about insignificant whitespace. It should also be written into Yoyodyne since `twiml.rb` is generated.
The purpose of this PR is to properly use all of Nokogiri's features to generate the XML, including the header, and fixes what seems like an inconsistency, in which the XML is generated from a `Node` instead of the whole `Document`.

Fixes xml generation

---

lib/twilio-ruby/framework/error.rb
lib/twilio-ruby/framework/version.rb

Based on feedback from https://betta.io/blog/2018/03/30/graceful-errors-in-ruby-sdks/.
With the following code:
```ruby
require './lib/twilio-ruby'
account_sid = ENV['TWILIO_ACCOUNT_SID']
auth_token = ENV['TWILIO_AUTH_TOKEN']
client = Twilio::REST::Client.new account_sid, auth_token
client.messages.create
```
the error message before looks like:
```
/Users/pnash/projects/ruby-projects/twilio-ruby/lib/twilio-ruby/framework/version.rb:157:in `create': Unable to create record: A 'From' phone number is required. (Twilio::REST::RestError)
from /Users/pnash/projects/ruby-projects/twilio-ruby/lib/twilio-ruby/rest/api/v2010/account/message.rb:71:in `create'
from test.rb:23:in `<main>'
```
But with this change, looks like:
```
/Users/pnash/projects/ruby-projects/twilio-ruby/lib/twilio-ruby/framewor …
```

Improves error message for Twilio::REST::RestError.

---

lib/twilio-ruby/jwt/access_token.rb
spec/jwt/access_token_spec.rb

https://issues.corp.twilio.com/browse/CLIENT-4492
To support JS Clients per this spec:
https://paper.dropbox.com/doc/Proposal-FPA-Token-Format-for-Programmable-Voice-SDKs-xhdFHD6N3aPW9GRp4dXNX

Add incoming.allow to AccessToken VoiceGrant

---

lib/rack/twilio_webhook_authentication.rb
lib/twilio-ruby.rb
lib/twilio-ruby/framework/domain.rb
lib/twilio-ruby/framework/error.rb
lib/twilio-ruby/framework/helper.rb
lib/twilio-ruby/framework/obsolete_client.rb
lib/twilio-ruby/framework/page.rb
lib/twilio-ruby/framework/request.rb
lib/twilio-ruby/framework/resource.rb
lib/twilio-ruby/framework/response.rb
lib/twilio-ruby/framework/serialize.rb
lib/twilio-ruby/framework/twilio_response.rb
lib/twilio-ruby/framework/values.rb
lib/twilio-ruby/framework/version.rb
lib/twilio-ruby/http/http_client.rb
lib/twilio-ruby/jwt/access_token.rb
lib/twilio-ruby/jwt/client_capability.rb
lib/twilio-ruby/jwt/jwt.rb
lib/twilio-ruby/jwt/task_router.rb
lib/twilio-ruby/security/request_validator.rb
lib/twilio-ruby/util.rb
lib/twilio-ruby/util/configuration.rb
lib/twilio-ruby/version.rb

This should help reduce the memory footprint of the gem as reported in #396.
---

Adds frozen_string_literal magic comment.

---

lib/twilio-ruby/twiml/twiml.rb
spec/twiml/messaging_response_spec.rb
spec/twiml/voice_response_spec.rb

Does what it says on the tin.
```ruby
voice_response = Twilio::TwiML::VoiceResponse.new
voice_response.comment("hello")
voice_response.to_s
```

Allows developers to add comments to TwiML

---

.travis.yml
README.md

These rubies have now been end-of-life for over a year.

Remove support for ruby 2.0 and 2.1, adds 2.5

---

lib/twilio-ruby/security/request_validator.rb
spec/security/request_validator_spec.rb

Key thing to consider for this implementation:
Because you can't overload in Ruby, I propose here checking if `params_hash` is `Enumerable`. If not, then we assume it's just a string (because `params_to_hash` has already attempted to convert it to a hash), which means it's a POST body instead of argument array.
This also refactors the tests to be in line with tests in the other libraries, removing redundant tests.

Add a request body validator

---

spec/twiml/voice_response_spec.rb

Show how to generate a `say-as` tag with the `interpret-as` attribute

Add a test showing how to emit "interpret-as"

---

.travis.yml
twilio-ruby.gemspec

Turns out we didn't need jruby-openssl. I thought it was required for
the signature verification but it turns out that JRuby ships enough
OpenSSL to do what we need (https://www.jruby.org/openssl).
Forcing an install of bundler on Travis is unnecessary too. Travis will
install a version of bundler and as long as it is within our supported
range it should work. Forcing an install will make Travis try to install
bundler on Ruby 2.2 which no longer works as Bundler 2 only supports
Ruby 2.3 and up.

Remove jruby-openssl requirement.

---

lib/twilio-ruby/security/request_validator.rb
spec/security/request_validator_spec.rb

Our internal system sends the bodySHA256 parameter as hex, not base64, so this PR fixes that.

Switch body validator to use hex instead of base64

---

lib/twilio-ruby/http/http_client.rb

While I was working on [this tutorial](https://github.com/TwilioDevEd/twilio-ruby-custom-client) I faced some issues regarding proxy usage with this library's HTTP Client: #390 
This PR attemps to fix that and also changed the way proxy address is assigned to Faraday, so it cannot complain for future releases.

breaking: Added proxy protocol to HTTP Client constructor

---

lib/twilio-ruby/http/http_client.rb

Fix line length to comply with rubocop constraints. I think #399 should have not passed `make lint`?

Reduce line length to satisfy rubocop constraints

---

.travis.yml
README.md

All support for Ruby 2.3 ended earlier this year: https://www.ruby-lang.org/en/news/2019/03/31/support-of-ruby-2-3-has-ended/
Ruby 2.6 was released earlier this year: https://www.ruby-lang.org/en/news/2018/12/25/ruby-2-6-0-released/

Drop support for Ruby < 2.4 and add 2.6

---

README.md
lib/twilio-ruby/http/http_client.rb
spec/http/http_client_spec.rb

breaking: Catch and wrap Faraday client errors

---

.gitignore
lib/twilio-ruby/security/request_validator.rb
spec/security/request_validator_spec.rb

added request validation for urls with and without ports

---

lib/twilio-ruby.rb
lib/twilio-ruby/twiml/twiml.rb

Works towards fixing #396.
Others are reporting that `twilio-ruby` takes a lot of memory. My belief is that this is because it is a large library that covers an ever increasing API surface. The issue is not necessarily in that the library is so large, but that the entire thing is loaded in one go with `require`s for days.
I am going to send a few PRs that update our use of `require` to `autoload` where appropriate. `autoload` only loads the file when the constant (class/module) is used. In this first PR, for those who include the library but don't use TwiML, the files governing TwiML creation will not be loaded into memory. For those that do use TwiML the behaviour will be unchanged. Notably this also moves requiring `nokogiri` to the TwiML files too. This will not affect a Rails user, …

chore: autoload TwiML to save memory on load

---

twilio-ruby.gemspec

Relates to https://github.com/twilio/twilio-ruby/pull/489

fix: loosen the faraday version requirement

---

.travis.yml

This PR removes the no-longer-used Travis setting `sudo: false`. See [more at the Travis blog](https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration).

chore: Travis: Drop unused "sudo: false" directive

---

twilio-ruby.gemspec

This PR changes the gemspec's `homepage` property to use `https://`.

chore: Refer to https:// homepage in gemspec

---

CHANGES.md
CONTRIBUTING.md
README.md

chore: update GitHub branch references to use HEAD

---

spec/spec_helper.rb

Rubocop flagged line for [NonDeterministicRequireOrder](https://docs.rubocop.org/rubocop/cops_lint.html#lintnondeterministicrequireorder) lint check. Sorting the returned list before requiring makes the order deterministic.

chore: sort files for deterministic require order

---

lib/twilio-ruby/framework/version.rb
spec/framework/version_spec.rb
spec/holodeck/holodeck.rb

Dropping the page limit calculation since it doesn't make sense to be calculated from a record limit.
Relates to https://github.com/twilio/twilio-python/pull/523

fix: drop the page limit calculation

---

lib/twilio-ruby/framework/version.rb
spec/framework/version_spec.rb

Fetching a BulkExport for a single day returns a `307` with the AWS URL for the file. With this change, the URL will now be included in the response.
Fixes https://github.com/twilio/twilio-ruby/issues/532

fix: allow API redirect responses

---

lib/twilio-ruby/jwt/access_token.rb
spec/jwt/access_token_spec.rb

This PR adds AccessTokenOptions.region parameter to support regional authentication. This value will be encoded in the twr header of the JWT. If the parameter is not specified or invalid, no twr value is added. See this document for more details.
JIRA: https://issues.corp.twilio.com/browse/CLIENT-8142
I was unable to find any existing documentation for the file I modified. Please point me to the right file to make documentation changes, if a place exists.

feat: Add region to AccessToken

---

.travis.yml
spec/twiml/voice_response_spec.rb

The code is correct in the `VoiceResponse`, but the test is wrong. The body of a task is a JSON object, so the argument should be a hash. Originally this was implemented, in the test, as a hash omitting the curly braces, however Ruby 3 is more strict about how hashes and keyword arguments work together. To submit the body as a hash, you can no longer omit the braces. Once that was fixed, the tests all pass under Ruby 3.

fix: Adds Ruby 3.0 to Travis. Fixes test.

---

twilio-ruby.gemspec

The `test_files` attribute was already being set in `twilio-ruby.gemspec`, but this does not prevent the test files from being added to the .gem bundle and installed onto the system/image.
Prevent spec/test files from being added to the bundle in the first place by adding a `reject` filter. This practice is now the default when creating new gems: https://github.com/rubygems/rubygems/blob/85677a06a727d5053e9f4a3f13355775ed1e0fd5/bundler/lib/bundler/templates/newgem/newgem.gemspec.tt#L27-L31
This change shrinks the disk space used by about ~4.5 MB:
```
du -sh /opt/local/lib/ruby/gems/2.7.0/gems/twilio-ruby-5.*
13M     /opt/local/lib/ruby/gems/2.7.0/gems/twilio-ruby-5.48.0
8.6M    /opt/local/lib/ruby/gems/2.7.0/gems/twilio-ruby-5.50.0
```
**I don't …

chore: omit spec/ from .gem file

---

lib/twilio-ruby/http/http_client.rb
spec/http/http_client_spec.rb

This PR aims to fix the JSON::ParserError (reported on issue #544) when the client returns a
timeout response by skipping parsing the response body when the response
status code is 504.

fix: JSON parser error on timeout response

---

README.md
lib/twilio-ruby/http/http_client.rb
spec/http/http_client_spec.rb

Add the `configure_connection` method to the `Twilio::HTTP::Client` class to allow consumers to apply custom configuration to the Faraday connection. 
The motivation for this change is to allow consumers to register custom middleware.

feat: Add `Twilio::HTTP::Client#configure_connection`

---

lib/twilio-ruby/http/http_client.rb

warning:
> WARNING: `Faraday::Connection#basic_auth` is deprecated; it will be removed in version 2.0.
> While initializing your connection, use `#request(:basic_auth, ...)` instead.
> See https://lostisland.github.io/faraday/middleware/authentication for more usage info.

Fix: deprecation warning on Faraday

---

.github/workflows/test.yml
.rubocop.yml
Makefile
twilio-ruby.gemspec

Rubocop linting fails on `ruby-head` tests (aka ruby `v3.1.0`). Response from [rubocop team](https://github.com/rubocop/rubocop/issues/10258) is to upgrade from rubocop `0.82.0` to `v1.22.3`. We cannot do this until we drop support for ruby v2.4 in this helper. This PR allows test workflows to run and pass with success even if the single ruby-head test fails.

chore: make ruby-head test optional

---

.github/workflows/test-and-deploy.yml
Gemfile
sonar-project.properties
spec/spec_helper.rb

Added sonarcloud analysis to the build

chore: Add sonarcloud analysis

---

lib/rack/twilio_webhook_authentication.rb
spec/rack/twilio_webhook_authentication_spec.rb

The webhook authentication middleware has been using the return value of `request.POST` to determine the params to validate, assuming it returns a non-`Hash` in the case of a non-formish-POST. However, this is not true, though perhaps it was at some point in the past:
https://github.com/rack/rack/blob/8c9a97fe6073a8f4c17f85fff20f20eae22d1bcb/lib/rack/request.rb#L451-L478
This means the `RequestValidator` body validation code is entirely skipped over, since `params_hash` is always `Enumerable`:
https://github.com/twilio/twilio-ruby/blob/6c50e0fa13bfefdcdaaa0799b8798023ce492e60/lib/twilio-ruby/security/request_validator.rb#L34-L39
So the body is always considered valid, and only the URL signature is ever validated:
https://github.com/twilio/twilio-ruby/blob/6c50e0fa13bfefdcdaaa0799b8798023ce …

fix: Validate signatures in Rack middleware for non-form-data payloads

---

lib/twilio-ruby.rb
spec/spec_helper.rb

Now that the webhook authentication requires part of Rack to run, loading the gem in a context that doesn't include Rack fails. For most people this won't happen as it will be used in the context of a web framework and most Ruby web frameworks rely on Rack. However, simple scripts that don't have Rack loaded will fail because the application can't load rack/media_type. In these cases, since Rack is not present, rack middleware won't be helpful either, so we only load the Rack middleware if Rack is present.

fix: don't load webhook authentication if Rack not present

---

lib/twilio-ruby.rb

Fixes #605 
Only require the twilio_webhook_authentication functionality if the Rack version is > 2.
FYI, #602 attempted to fix this, but doesn't work when the Rack version is < 2.

fix: Only require twilio_webhook_authentication if Rack version > 2

---

lib/twilio-ruby/rest/client.rb
spec/rest/client_spec.rb

Modify retrieval of os name and arch with Ruby Config instead of linux commands
https://github.com/twilio/twilio-ruby/pull/604#issuecomment-1114624543

fix: Retrieval of OS Info with Ruby Config for User Agent string

---

lib/twilio-ruby/security/request_validator.rb
spec/security/request_validator_spec.rb

Fixes #613 
I ran into this issue when I wrongly expected JSON requests I am making from a Twilio serverless function to one of my services to be correctly verified. I know that Twilio will always include the `bodySHA256` query parameter for JSON requests. But if you use `Twilio::Security::RequestValidator#validate` in a custom way you might pass the wrong URL and in that case it shouldn't crash.

fix: Make RequestValidator#validate fail if URL has no query params

---

twilio-ruby.gemspec

Closes #625 by increasing the maximum allowed version of the [ruby-jwt gem](https://github.com/jwt/ruby-jwt) to be 2.6.

chore: Bump jwt version max version to 2.6

---

lib/twilio-ruby/rest.rb

Otherwise if there happens to be `.rb` in a directory name, that'll be incorrectly modified as well.
I haven't added a test as this code is part of loading everything, rather than something that occurs once the library is loaded.

fix: match only against the end of a file path.

---

lib/twilio-ruby/rest/video/v1/recording.rb

Fix local jump error due to lack of block passing for recording list.
Fixes
https://github.com/twilio/twilio-ruby/issues/663
It appears after a recent merge that the block passed to the seralize_list method was removed in the recordings file:
https://github.com/JYorston/twilio-ruby/commit/1956b94a670527a2886d64ac72a596e84247b4f5
This is causing a local_jump_error when trying to list recordings on the latest Gem version.
I added the block back in and verified that it is now working as expected.
Checklist

fix: #663 local jump error due to lack of block passing for recording list

---

lib/twilio-ruby/framework/request.rb
lib/twilio-ruby/http/http_client.rb

Added middleware for aplication/json and corrected to_s() for request in case of json body

chore: set middleware for json type

---

.dockerignore
Dockerfile

This has been tested locally by creating container out of image with the changes in current PR.
```
root@3b861089fc6f:/twilio# ls
Gemfile  Gemfile.lock  LICENSE	README.md  Rakefile  lib  pkg  twilio-ruby.gemspec 
```

chore: create image with required files

---

.github/workflows/test-and-deploy.yml

Failing job - https://github.com/twilio/twilio-ruby/actions/runs/14993570192/job/42122563880
`ruby-head` on CI is built from the latest commit(s) on Ruby’s master branch - https://github.com/ruby/ruby
It seems that there might be some unstable changes in the branch which leads to test failure. Removing the version for now, to pass the tests

chore: removing ruby-head from CI
